Add markdown linter for doc wrapping
Quansight/qhub pull request #1152
Opened 2022-03-08 19:08 UTC by viniciusdc

Closes #1113  

## Changes introduced in this PR:

- Add [`mdformat`](https://github.com/executablebooks/mdformat) to wrap doc lines, explicitly added the configuration toml to further change in the default settings. 
- Set wrap line length to 180.

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

### Requires testing

- [ ] Yes
- [x] No

## Further comments (optional)

Any wrapping will automatically happen when a `.md` file is committed.

2022-03-08 20:13 UTC, tonyfast approved these changes
seems reasonable to me.  is 180 a lot of characters?

i wish that mdformat used the pyproject convention for configuration instead of adding another file. :(

2022-03-08 20:16 UTC, costrouc requested changes
@viniciusdc this looks good to me. Following this PR could you make a giant commit of strictly only the formatting changes?

2022-03-08 20:17 UTC, costrouc approved these changes

2022-03-08 23:12 UTC, viniciusdc commented
> seems reasonable to me. is 180 a lot of characters?
> 
> i wish that mdformat used the pyproject convention for configuration instead of adding another file. :(

Hi @tonyfast, indeed that would be great, they have an open PR to read from `pyproject.toml`, so maybe we can remove that extra file in the future. About the 180, I was following the original idea from this linked issue, and as there doesn't seem to be accordance about the best line length for documentation... having this as a maximum might be tolerable*.

 I would prefer 88 as the limit to wrap, but I don't want this to be a restriction imposed further in the docs. So my way of thinking about this 180, is that it is "the max" length that needs to be respected.

2022-03-08 23:12 UTC, viniciusdc commented
> @viniciusdc this looks good to me. Following this PR could you make a giant PR commit of strictly only the formatting changes?

Sure, I think it would be best to add those changes within this PR as its the source of the changes...

2022-03-09 14:38 UTC, viniciusdc commented
Sorry for the force-pushing, I tried to include the formatted docs, but creating a different PR for that definitely is the best path to go.

2022-03-10 16:43 UTC, merged