Make conda-store image tag configurable
Quansight/qhub pull request #1391
Opened 2022-08-10 17:29 UTC by iameskild

Fixes | Closes | Resolves #

> Please remove anything marked as optional that you don't need to fill in.
> Choose one of the keywords preceding to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666).
> If there is no issue, remove the line. Remove this note after reading.

## Changes introduced in this PR:

A minor change that will enable users to manually update the conda-store image tag as needed. The benefit of this change is that users can choose to update conda-store without having to wait for a new qhub release. 

## Types of changes

What types of changes does your PR introduce?

_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

### Requires testing

- [ ] Yes
- [ ] No

### In case you checked yes, did you write tests?

- [ ] Yes
- [ ] No

## Documentation

Does your contribution include breaking changes or deprecations?
If so have you updated the documentation?

- [ ] Yes, docstrings
- [ ] Yes, main documentation
- [ ] Yes, deprecation notices

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered and more.

2022-08-10 18:44 UTC, costrouc requested changes

2022-08-10 18:44 UTC, costrouc commented on qhub/stages/input_vars.py
> +        "conda-store-image-tag": config.get("conda-store", {}).get("image_tag", None),
I think the PR will pass with this change.

2022-08-10 19:56 UTC, iameskild commented on qhub/stages/input_vars.py
> +        "conda-store-image-tag": config.get("conda-store", {}).get("image_tag", None),
Passing `None` as a default didn't work so I added `DEFAULT_CONDA_STORE_IMAGE_TAG` to `constants.py`.

2022-08-11 00:39 UTC, costrouc approved these changes

2022-08-11 00:39 UTC, merged