ci: add support for develop branch
Quansight/qhub pull request #1410
Opened 2022-08-19 07:55 UTC by HarshCasper

2022-08-30 17:31 UTC, trallard requested changes

2022-08-30 17:31 UTC, trallard commented on .github/workflows/kubernetes_test.yaml
> +      - name: "Set QHUB_IMAGE_TAG=develop"
This hardcodes for `develop` and drops `main` altogether - the idea is that it works for both not one or the other. 
Could leverage GH actions context to get the branch/ref name and set here

2022-08-30 17:31 UTC, trallard commented on .github/workflows/kubernetes_test.yaml
> +          echo "QHUB_IMAGE_TAG=develop" >> "$GITHUB_ENV"
same as above

2022-08-31 10:15 UTC, trallard commented
After going over the release workflow - and migration tasks - it does seem we need the workflow to run against `main` AND release branches, so we'd need something like:


`branches: [ main, 'release/v[0-9].[0-9]+' ]` cc @costrouc  ofc need to agree on the `release` prefix - but I think that should be a reasonable branching strategy WDYT?

2022-09-08 14:51 UTC, trallard commented on .github/workflows/run-pre-commit.yaml
> +    branches: [ main, develop ]
we no longer have a develop branch - there is only a release (with the corresponding CalVer patter) and a main branch

2022-09-26 06:16 UTC, HarshCasper commented
Hi @trallard — Can you please have a look at it once again?

2022-09-26 06:25 UTC, closed without merging