add azure deploy guide
Quansight/qhub pull request #517
Opened 2021-04-22 22:48 UTC by Adam-D-Lewis

I added the azure deploy guide.   I also renamed it so Azure appears before Digital Ocean since I believe Azure is more popular than Digital Ocean as a cloud provider.

2021-04-24 13:42 UTC, laisbsc requested changes
I've made these superficial changes but since the config file changed a lot, it might be the case to update some of the changes to the latest version as well.
For now, I think we can commit these and I need to think about how to update the entire config docs stack to the newest version.

2021-04-24 13:42 UTC, laisbsc commented on docs/source/04_how_to_guides/3_qhub-azure-deploy_guide.md
> +An image is the term used to refer to a serialized copy of the state of an environment stored in a file. Default images section in the configuration file lists the images used to run the default imag
```suggestion
An **image** is the term used to refer to a serialized copy of the state of an environment stored in a file. The `default images` section in the QHub configuration file lists the images used to run the default image (if not already specified in a *profile* - described in the next section). For example, the `jupyterhub` key controls the JupyterHub image run.
```

2021-04-24 13:42 UTC, laisbsc commented on docs/source/04_how_to_guides/3_qhub-azure-deploy_guide.md
> +This section allows you to control the amount of storage allocated to shared filesystems. Please note, when you change the storage size, it will delete the previous storage.
```suggestion
This section controls the amount of storage allocated to shared filesystems.
> NOTE: When the storage size is changed, the previous storage will be deleted.
```

2021-04-24 13:42 UTC, laisbsc commented on docs/source/04_how_to_guides/3_qhub-azure-deploy_guide.md
> +Profiles are used to control the jupyterlab user instances and dask-workers provided by dask-gateway.
```suggestion
Profiles are used to control the `jupyterlab` user instances and `dask-workers` provided by Dask-Gateway.
```

2021-04-24 13:47 UTC, laisbsc commented on docs/source/04_how_to_guides/3_qhub-azure-deploy_guide.md
> +This section allows you to control the amount of storage allocated to shared filesystems. Please note, when you change the storage size, it will delete the previous storage.
This section also handles the storage for conda-store, right?

2021-05-05 18:41 UTC, costrouc commented
@Adam-D-Lewis could you make the requested changes? Happy to add the azure docs and thanks for the review @laisbsc :smile:

2021-05-19 11:28 UTC, danlester approved these changes

2021-05-19 11:38 UTC, merged