Prometheus grafana
Quansight/qhub pull request #733
Opened 2021-07-14 15:04 UTC by Adam-D-Lewis

Initial integration of prometheus/grafana into qhub.  I tested it locally and it seems to be working.

2021-07-14 15:05 UTC, Adam-D-Lewis commented on qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/ingress/main.tf
> +            "--log.level=DEBUG", #${var.loglevel}",
oops, didn't mean to commit this.  I'll undo this.

2021-07-14 16:14 UTC, costrouc commented
I'd prefer if we could pull in the helm charts similar to https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/jupyterhub/main.tf#L6. This still pins the chart to a particular version. Is there a reason that we are copying the entire chart locally?

2021-07-14 16:20 UTC, Adam-D-Lewis commented
@costrouc I was following the example of what was done for the clearml (https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/clearml), but I don't think there is anything preventing us from importing the chart.  @aktech any thoughts for or against putting the entire helm chart in the repo?

2021-07-15 08:05 UTC, aktech commented
@Adam-D-Lewis I agree with @costrouc we shouldn't put helm charts in the repository. ClearML was a special case, as we had to modify the chart. Also, since the last update on ClearML, I'll see if we can remove the ClearML charts as well.

2021-07-16 15:05 UTC, Adam-D-Lewis commented
@costrouc ready for a re-review when you are able, thanks!

2021-07-22 13:43 UTC, aktech commented
Do you know why is the Kubernetes tests failing?

2021-07-22 13:54 UTC, aktech commented on qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/modules/kubernetes/services/monitoring/values-monitoring-qhub.yaml
> +     domain: github-actions.qhub.dev
I believe this has to be custom for each deployment. This is

2021-07-22 14:00 UTC, aktech requested changes
It seems like the following files can be removed:

- `values-monitoring-qhub.yaml`
- `values-original.yaml`

Also the diff between the original and overridden files is just following:

```diff
❯ diff values-original.yaml values-monitoring-qhub.yaml
628a629,637
>
>   grafana.ini:
>     server:
>      # The full public facing url you use in browser, used for redirects and emails
>      domain: github-actions.qhub.dev
>      root_url: "%(protocol)s://%(domain)s/monitoring"
>      server_from_sub_path: true
>      router_logging: true
>      enable_gzip: true
732c741
<
---
>
```

Which means you can set the particular values via [terraform's helm `set` attribute](https://registry.terraform.io/providers/hashicorp/helm/latest/docs#example-usage).

2021-07-22 14:06 UTC, aktech commented on docs/source/introduction.md
> ++ [**prometheus**](https://grafana.com/) cluster monitoring
typo in the url for prometheus

2021-08-02 22:55 UTC, Adam-D-Lewis commented on docs/source/introduction.md
> ++ [**prometheus**](https://grafana.com/) cluster monitoring
fixed

2021-08-02 22:58 UTC, Adam-D-Lewis commented
>It seems like the following files can be removed:

>values-monitoring-qhub.yaml
values-original.yaml
Also the diff between the original and overridden files is just following:

❯ diff values-original.yaml values-monitoring-qhub.yaml
628a629,637
>
>   grafana.ini:
>     server:
>      # The full public facing url you use in browser, used for redirects and emails
>      domain: github-actions.qhub.dev
>      root_url: "%(protocol)s://%(domain)s/monitoring"
>      server_from_sub_path: true
>      router_logging: true
>      enable_gzip: true
732c741
<
---
>
>Which means you can set the particular values via terraform's helm set attribute.

I made the requested changes.

2021-08-03 09:21 UTC, aktech commented
Waiting for the tests to pass here: https://github.com/Quansight/qhub/pull/748 to see if the failed K8s tests in here are relevant or not.

2021-08-03 12:16 UTC, aktech commented
Seems like the tests pass on main, can you check why k8s tests fail? I can rerun again to confirm,

2021-08-10 16:57 UTC, Adam-D-Lewis commented
Cyprus says there is insufficient cpu on the node with the additional pods in this PR.  Maybe I can reduce the used cpu or maybe we can use CIrun

2021-08-11 14:10 UTC, Adam-D-Lewis commented
Blocked by https://github.com/Quansight/qhub/issues/756

2021-08-13 15:23 UTC, costrouc commented
Could you add an entry to the changelog?

2021-08-13 15:30 UTC, costrouc approved these changes

2021-08-13 15:30 UTC, merged